name       : libkeduvocdocument
version    : 18.12.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/libkeduvocdocument-18.12.0.tar.xz : 53f8edc5db71be5a1ccd3a66155470ea86ae65a404de85025b0a67c5eebb46b9
license    : GPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
