name       : libkeduvocdocument
version    : 20.12.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/libkeduvocdocument-20.12.0.tar.xz : a6df8eb7f5269f4853bee0491c6cd9d15631e734f67dddc17d7e9091443e049e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
