name       : libkeduvocdocument
version    : 18.04.2
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/libkeduvocdocument-18.04.2.tar.xz : f5c7901bdb6a0ad528f54844a6d7952952e9c06527d46c110840052793d46f9d
license    : GPL-2.0
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
