name       : libkeduvocdocument
version    : 18.04.3
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/libkeduvocdocument-18.04.3.tar.xz : 9f430a766909d0cd1b51d7d3172d12a788d7bcb731e71f82e6e1b8d3eeba4df4
license    : GPL-2.0
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
