name       : libkeduvocdocument
version    : 21.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/libkeduvocdocument-21.04.1.tar.xz : 5bb7318dbea9783cb14fa0c9c85c6034da4efa9ebdb6cd0a20c159ba56f31034
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Xml)
    - karchive-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
