name       : libkeduvocdocument
version    : 20.12.2
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/libkeduvocdocument-20.12.2.tar.xz : c6701525781f0cf9c4e4173cfa0bb26e2fd5d1098fbfbe84d6cf0bb42b307152
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Xml)
    - karchive-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
