name       : libkeduvocdocument
version    : 21.08.3
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/libkeduvocdocument-21.08.3.tar.xz : 01b3cf408ecf16991cc9716b18b4f875e6812ebbae69545ac4e3feb08b2fd1e3
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Xml)
    - karchive-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
