name       : libkeduvocdocument
version    : 20.08.1
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/libkeduvocdocument-20.08.1.tar.xz : ecd158beb7fcc1a5d540d956669c6fdce6172f4b282755170d2791076d75ad84
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
