name       : libkeduvocdocument
version    : 17.12.1
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/libkeduvocdocument-17.12.1.tar.xz : b2739eadec5abbcde72fe5de9e921c4b8390d2cc58c2841252ae70143c74d061
license    : GPL-2.0
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files.
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
