name       : libkeduvocdocument
version    : 18.04.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/libkeduvocdocument-18.04.1.tar.xz : f95f7d1a149dd7364ce0c56973a6badf76b96b116fe6e2c15f694ce5242f2292
license    : GPL-2.0
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files.
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
