name       : libkeduvocdocument
version    : 16.12.1
release    : 1
source     :
    - http://download.kde.org/stable/applications/16.12.1/src/libkeduvocdocument-16.12.1.tar.xz : 4e83691f63ddddc76178cd6796d87ee13ae7ee8f81a954bde21bff7dcc5e78e8
license    : GPL-2.0
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files.
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
