name       : libkeduvocdocument
version    : 21.12.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/libkeduvocdocument-21.12.3.tar.xz : 60d36549eb3b615d285cb8d3c4ae7dc281be980ff3c1b4df52c5772c643c739a
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Xml)
    - karchive-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
