name       : libkeduvocdocument
version    : 17.08.3
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/libkeduvocdocument-17.08.3.tar.xz : 75fd8d24da0cb8aba0b02209c199db9a3dec466216c7431cfd9ae5452c472761
license    : GPL-2.0
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files.
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
