name       : libkeduvocdocument
version    : 18.12.2
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/libkeduvocdocument-18.12.2.tar.xz : 073adeacfd1d048bc10d2447a5d72874a1fa0ddc23c58dbc67713bb89d7d5cb4
license    : GPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
