name       : libkeduvocdocument
version    : 19.04.2
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/libkeduvocdocument-19.04.2.tar.xz : 18017cc126ba16a34bc8a266630368c3e5a1611ebbc09a29af8184157a161de6
license    : GPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
