name       : libkeduvocdocument
version    : 21.08.2
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/libkeduvocdocument-21.08.2.tar.xz : becee3a88b9ba16ebcb1fa94a6154c7f7d73d8ff3600072fb6725f9a17ff3514
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Xml)
    - karchive-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
