name       : libkeduvocdocument
version    : 17.12.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/libkeduvocdocument-17.12.3.tar.xz : 3b0468bc374024bc2951685a84759f91ab192dd557579d0981ebc7605ca5117b
license    : GPL-2.0
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files.
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
