name       : libkeduvocdocument
version    : 19.04.1
release    : 24
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/libkeduvocdocument-19.04.1.tar.xz : c0b5e23a677cea13a2e15989a5b2240ddab2948b00be67e6306cf916e7ca2e59
license    : GPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Library to parse, convert, and manipulate KVTML files
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
