name       : libkeduvocdocument
version    : 17.08.2
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/libkeduvocdocument-17.08.2.tar.xz : d7eb665963f55344065a42900b05cddaaa10f8c2e8511149571d7f520a3d9269
license    : GPL-2.0
component  : desktop.library
summary    : Library to parse, convert, and manipulate KVTML files.
description: |
    Contains KEduVocDocument and its related class for reading from/writing to the KVTML format (and others too).
builddeps  :
    - pkgconfig(Qt5Xml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
